### PR TITLE
Updated TextSpan

### PR DESCRIPTION
**Pull request by prasadsunny1**
TextSpan parent can have a style that all other children can inherit.
Children can alter their own style if needed.

### CODE REVIEW

**Comment by prasadsunny1** [comment]
and also tell me if I made this pull request correctly.

**Comment by ibhavikmakwana** [comment]
Yes, you have created the PR correctly,
If you implement the new feature in the repo then create a new branch like `feature-featureName` and make PR using that branch.

**Comment by ibhavikmakwana** [comment]
@all-contributors please add @prasadsunny1

**Comment by ibhavikmakwana** [comment]
@all-contributors please add @prasadsunny1 for code

**Pull request merged**
